name: Test CSV no vulns

on:
  push:
    branches: #
      - '*'

jobs:
  daily_job:
    runs-on: ubuntu-latest
    environment:
      name: plugin-development

    steps:

      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}

      - name: Test container scan
        id: inspector
        uses: aws-actions/vulnerability-scan-github-action-for-amazon-inspector@v1
        with:
          artifact_type: 'container'
          artifact_path: 'alpine:latest'
          display_vulnerability_findings: "enabled"
          sbomgen_version: "latest"

      - name: Display scan results
        run: cat ${{ steps.inspector.outputs.inspector_scan_results_csv }}
        
      - name: Display scan results (JSON)
        run: cat ${{ steps.inspector.outputs.inspector_scan_results }}

      - name: Display package vulns (CSV)
        run: cat ${{ steps.inspector.outputs.inspector_scan_results_csv }}

      - name: Display package vulns (MD)
        run: cat ${{ steps.inspector.outputs.inspector_scan_results_markdown }}

      - name: Display Dockerfile vulns (CSV)
        run: cat ${{ steps.inspector.outputs.inspector_dockerfile_scan_results_csv }}

      - name: Display Dockerfile vulns (MD)
        run: cat ${{ steps.inspector.outputs.inspector_dockerfile_scan_results_markdown }}
